### ISSUE TITLE
安卓12上无法删除Android/data内的文件

### ISSUE THREAD

**Issue by Rambin** [Rambin/ESFileExplorerUnofficialBugTracker#1]
手机型号：OnePlus 9 Pro
系统：ColorOS 12 (Android 12)
ES版本：4.2.9.3
在安卓11的手机（OnePlus 7 Hydrogen OS 11 Android 11）上没有复现

**Comment by VoidK2** [comment]
done

**Comment by Rambin** [comment]
已在4.2.9.5修复
